config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    has_rich_text :description 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
  has_one_attached :avatar

  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize_to_limit: [100, 100])   
   else
     "user.svg"
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password, :avatar)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password, :avatar)}
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :project, :owner, :status, :required_by, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Kanban</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="flex flex-row justify-end pr-4 mt-2">
      <% if user_signed_in? %>
        <%= link_to "Edit Account", edit_user_registration_path %>
        <div class="h-6 w-6 rounded-full ring-2 ring-white overflow-hidden mx-2">
            <%= image_tag (current_user.avatar_thumbnail) %>
        </div>
        <div class="mr-2">
          <%= current_user.email %>
        </div>
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
        <% else %>
        <%= link_to "Sign in", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </div>
    <main class="container mx-auto mt-28 px-5 flex mb-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "contents") do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :project %>
    <%= form.text_field :project, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :owner %>
    <%= form.text_field :owner, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :required_by %>
    <%= form.datetime_field :required_by, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :completed %>
    <%= form.datetime_field :completed, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
<% if action_name != "index" %>
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= task.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= task.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Project:</strong>
    <%= task.project %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Owner:</strong>
    <%= task.owner %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= task.status %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Required by:</strong>
    <%= task.required_by %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Completed:</strong>
    <%= task.completed %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this task", task, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this task', edit_task_path(task), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>

  <% else %>
  <div class="w-56 h-80 border-2 rounded-md shadow
  transition ease-in-out hover:bg-gray-100 duration-200">
    <p class="text-lg font-semibold text-center mb-1">
      <%= task.title %>
    </p>
    <div class="container mx-auto max-w-md max-h-48 mb-1">
    <p class="text-center">
    <%= task.description %>
    </p>
    </div>
    <p class="text-center">
      <%= task.project %>
    </p>

    <p class="text-center">
      <%= task.owner %>
    </p>
    <% if task.completed.nil? %>
    <p class="text-center text-xs ">
      <strong class="font-medium">Required by</strong>
      <%= time_tag task.required_by, "data-local": "weekday-or-date" %>
    </p>
    <% end %>
    <% if !task.completed.nil? %>
      <p class="mx-auto text-center text-xs border rounded-lg bg-green-300 w-16">
        <%= time_tag task.completed,"data-local": "time-ago" %>
      </p>
    <% end %>
    <div class="flex flex-row justify-center space-x-4 my-1">
    <% if action_name != "show" %>
      <%= link_to task do %>
        <div class="w-6">
          <%= image_tag "eye.svg", id:"eye" %>
        </div>
      <% end %>

      <%= link_to edit_task_path(task) do %>
       <div class="w-6">
          <%= image_tag "pencil.svg", id:"pencil" %>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/tasks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing task</h1>

  <%= render "form", task: @task %>

  <%= link_to "Show this task", @task, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to tasks", tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tasks/index.html.erb
<div class="w-full h-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-4 -mt-16">
    <h1 class="text-lg font-bold text-4xl">Kanban Tasks</h1>
    <%= link_to 'New task', new_task_path, class: "rounded-lg py-3 px-5 bg-gray-800 text-white block font-medium" %>
  </div>

  <div id="tasks" class="grid grid-cols3 gap-4">
    <div class="border rounded-md bg-gray-100">
      <p class="font-semibold text-center">Work Queue</p>
    </div>    
    <div class="border rounded-md bg-gray-200">
      <p class="font-semibold text-center">In Progress</p>
    </div>
    <div class="border rounded-md bg-gray-300">
      <p class="font-semibold text-center">Completed</p>
    </div>   
    <div class="col-start-1 gap-4 p-2 border rounded-lg flex flex-row flex-wrap">
      <%= render @tasks.where(:status => 'Work Queue') %>
    </div>
    <div class="col-start-2 gap-4 p-2 border rounded-lg flex flex-row flex-wrap">
      <%= render @tasks.where(:status => 'In Progress')  %>
    </div>
    <div class="col-start-3 p-2 gap-4 border rounded-lg flex flex-row flex-wrap">
      <%= render @tasks.where(:status => 'Completed')  %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="text-lg font-bold text-4xl">New task</h1>

  <%= render "form", task: @task %>

  <%= link_to 'Back to tasks', tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tasks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @task %>

    <%= link_to 'Edit this task', edit_task_path(@task), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this task', task_path(@task), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to tasks', tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>